---
name: HTML-Latemp-News
version: 0.1.7
author:
  - Shlomi Fish <shlomif@iglu.org.il>
abstract: |-
  News Maintenance Module for Latemp (and possibly other 
  web frameworks)
license: bsd
resources:
  license: http://www.opensource.org/licenses/bsd-license.php
requires:
  CGI: 0
  Class::Accessor: 0
  Test::More: 0
  XML::RSS: 0
provides:
  HTML::Latemp::News:
    file: lib/HTML/Latemp/News.pm
    version: 0.1.7
  HTML::Latemp::News::Base:
    file: lib/HTML/Latemp/News.pm
  HTML::Latemp::News::Item:
    file: lib/HTML/Latemp/News.pm
generated_by: Module::Build version 0.2703
